"""fix1 migration

Revision ID: 04bf16e2ae88
Revises: c37095f269d0
Create Date: 2025-03-30 17:51:40.009072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bf16e2ae88'
down_revision: Union[str, None] = 'c37095f269d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_custom_alias', 'short_urls', type_='unique')
    op.drop_constraint('uq_short_code', 'short_urls', type_='unique')
    op.drop_index('ix_short_urls_custom_alias', table_name='short_urls')
    op.create_index(op.f('ix_short_urls_custom_alias'), 'short_urls', ['custom_alias'], unique=True)
    op.drop_index('ix_short_urls_short_code', table_name='short_urls')
    op.create_index(op.f('ix_short_urls_short_code'), 'short_urls', ['short_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_urls_short_code'), table_name='short_urls')
    op.create_index('ix_short_urls_short_code', 'short_urls', ['short_code'], unique=False)
    op.drop_index(op.f('ix_short_urls_custom_alias'), table_name='short_urls')
    op.create_index('ix_short_urls_custom_alias', 'short_urls', ['custom_alias'], unique=False)
    op.create_unique_constraint('uq_short_code', 'short_urls', ['short_code'])
    op.create_unique_constraint('uq_custom_alias', 'short_urls', ['custom_alias'])
    # ### end Alembic commands ###
