"""fix5 migration

Revision ID: fc60b30fbbf7
Revises: 6c125a0d7f03
Create Date: 2025-03-31 22:24:43.698470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc60b30fbbf7'
down_revision: Union[str, None] = '6c125a0d7f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
